-- AlterTable
ALTER TABLE "colleges" ADD COLUMN     "aboutCollege" TEXT,
ADD COLUMN     "academicPressure" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "affiliation" TEXT,
ADD COLUMN     "annualFest" TEXT,
ADD COLUMN     "antiRagging" TEXT,
ADD COLUMN     "attendancePolicy" TEXT,
ADD COLUMN     "boysHostel" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "brochureUrl" TEXT,
ADD COLUMN     "campusSafety" TEXT,
ADD COLUMN     "campusSize" TEXT,
ADD COLUMN     "clubs" TEXT,
ADD COLUMN     "codingCulture" TEXT,
ADD COLUMN     "contactDetails" TEXT,
ADD COLUMN     "costOfLiving" TEXT,
ADD COLUMN     "culturalClubs" TEXT,
ADD COLUMN     "diversity" TEXT,
ADD COLUMN     "establishmentYear" INTEGER,
ADD COLUMN     "girlsHostel" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "googleMapsUrl" TEXT,
ADD COLUMN     "hasAuditorium" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasBankAtm" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasCafeteria" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasLabs" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasLibrary" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasMedicalCentre" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasSecurity" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasSmartClassrooms" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasSportsComplex" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasWifi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hostelAvailable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hostelCurfew" TEXT,
ADD COLUMN     "hostelFoodQuality" TEXT,
ADD COLUMN     "hostelHousekeeping" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hostelLaundry" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hostelRules" TEXT,
ADD COLUMN     "hostelSecurity" TEXT,
ADD COLUMN     "indiaTodayRank" INTEGER,
ADD COLUMN     "naacGrade" TEXT,
ADD COLUMN     "nbaStatus" TEXT,
ADD COLUMN     "ncc" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nearbyAirport" TEXT,
ADD COLUMN     "nearbyFlats" TEXT,
ADD COLUMN     "nearbyHospitals" TEXT,
ADD COLUMN     "nearbyMetro" TEXT,
ADD COLUMN     "nearbyPG" TEXT,
ADD COLUMN     "nearbyRailwayStation" TEXT,
ADD COLUMN     "nearbyRestaurants" TEXT,
ADD COLUMN     "nearbyShoppingAreas" TEXT,
ADD COLUMN     "nss" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "outlookRank" INTEGER,
ADD COLUMN     "ownership" TEXT,
ADD COLUMN     "qsRank" INTEGER,
ADD COLUMN     "researchCulture" TEXT,
ADD COLUMN     "societies" TEXT,
ADD COLUMN     "sports" TEXT,
ADD COLUMN     "startupCulture" TEXT,
ADD COLUMN     "studentEvents" TEXT,
ADD COLUMN     "studentSupport" TEXT,
ADD COLUMN     "technicalClubs" TEXT,
ADD COLUMN     "theWeekRank" INTEGER;

-- CreateTable
CREATE TABLE "college_courses" (
    "id" TEXT NOT NULL,
    "collegeId" TEXT NOT NULL,
    "field" TEXT NOT NULL,
    "degree" TEXT NOT NULL,
    "specialization" TEXT,
    "eligibility" TEXT,
    "entranceExam" TEXT,
    "cutoff" TEXT,
    "admissionProcess" TEXT,
    "documents" TEXT,
    "seatMatrix" TEXT,
    "reservation" TEXT,
    "counselling" TEXT,
    "managementQuota" TEXT,
    "tuitionFee" INTEGER,
    "registrationFee" INTEGER,
    "examFee" INTEGER,
    "hostelFee" INTEGER,
    "otherCharges" INTEGER,
    "totalCost" INTEGER,
    "refundPolicy" TEXT,
    "emiAvailable" BOOLEAN NOT NULL DEFAULT false,
    "educationLoanAvailable" BOOLEAN NOT NULL DEFAULT false,
    "placementPct" DOUBLE PRECISION,
    "avgPackage" DOUBLE PRECISION,
    "medianPackage" DOUBLE PRECISION,
    "highestPackage" DOUBLE PRECISION,
    "branchWisePlacement" TEXT,
    "internshipPct" DOUBLE PRECISION,
    "ppoPct" DOUBLE PRECISION,
    "topRecruiters" TEXT,
    "totalInvestment" INTEGER,
    "averageSalary" DOUBLE PRECISION,
    "expectedRoi" TEXT,
    "breakEvenTime" TEXT,
    "scholarshipsInfo" TEXT,
    "internshipsInfo" TEXT,
    "hackathons" TEXT,
    "researchProjects" TEXT,
    "exchangeProgram" TEXT,
    "startupCell" TEXT,
    "incubation" TEXT,
    "jobRoles" TEXT,
    "governmentJobs" TEXT,
    "higherStudies" TEXT,
    "certifications" TEXT,
    "studyAbroad" TEXT,
    "entrepreneurship" TEXT,
    "facultyRating" DOUBLE PRECISION,
    "placementRating" DOUBLE PRECISION,
    "courseRating" DOUBLE PRECISION,
    "curriculumRating" DOUBLE PRECISION,
    "verifiedReviewsCount" INTEGER,
    "qna" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "college_courses_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "college_courses_collegeId_idx" ON "college_courses"("collegeId");

-- AddForeignKey
ALTER TABLE "college_courses" ADD CONSTRAINT "college_courses_collegeId_fkey" FOREIGN KEY ("collegeId") REFERENCES "colleges"("id") ON DELETE CASCADE ON UPDATE CASCADE;
