-- Remove the Communities feature (full teardown): Posts/Feed, Pools, Help
-- Requests, Leadership (head applications), Ads, Discount claims, and the
-- community-scoped fields on Opportunity/Resource/Chat/Report/Complaint/Review.
--
-- Data-safety notes (hand-inserted, NOT auto-generated by `prisma migrate diff`):
--   1. Historical COMMUNITY_MANAGERS reviews become meaningless without their
--      community context, so they are deleted before reviews.communityId drops.
--   2. COMMUNITY-type chats have no title of their own today; backfill the
--      title from the community name before chats.communityId drops, so they
--      don't render as unnamed chats afterward (see messaging.service.ts's
--      listMyChats() title fallback: `chat.title ?? other?.profile?.fullName
--      ?? 'Group chat'`).

-- DropForeignKey
ALTER TABLE "ad_cards" DROP CONSTRAINT "ad_cards_communityId_fkey";

-- DropForeignKey
ALTER TABLE "ad_cards" DROP CONSTRAINT "ad_cards_createdById_fkey";

-- DropForeignKey
ALTER TABLE "bookmarks" DROP CONSTRAINT "bookmarks_postId_fkey";

-- DropForeignKey
ALTER TABLE "bookmarks" DROP CONSTRAINT "bookmarks_userId_fkey";

-- DropForeignKey
ALTER TABLE "chats" DROP CONSTRAINT "chats_communityId_fkey";

-- DropForeignKey
ALTER TABLE "comments" DROP CONSTRAINT "comments_authorId_fkey";

-- DropForeignKey
ALTER TABLE "comments" DROP CONSTRAINT "comments_parentId_fkey";

-- DropForeignKey
ALTER TABLE "comments" DROP CONSTRAINT "comments_postId_fkey";

-- DropForeignKey
ALTER TABLE "communities" DROP CONSTRAINT "communities_collegeId_fkey";

-- DropForeignKey
ALTER TABLE "community_head_applications" DROP CONSTRAINT "community_head_applications_communityId_fkey";

-- DropForeignKey
ALTER TABLE "community_head_applications" DROP CONSTRAINT "community_head_applications_userId_fkey";

-- DropForeignKey
ALTER TABLE "community_members" DROP CONSTRAINT "community_members_communityId_fkey";

-- DropForeignKey
ALTER TABLE "community_members" DROP CONSTRAINT "community_members_userId_fkey";

-- DropForeignKey
ALTER TABLE "complaints" DROP CONSTRAINT "complaints_communityId_fkey";

-- DropForeignKey
ALTER TABLE "discount_claims" DROP CONSTRAINT "discount_claims_claimedById_fkey";

-- DropForeignKey
ALTER TABLE "discount_claims" DROP CONSTRAINT "discount_claims_communityId_fkey";

-- DropForeignKey
ALTER TABLE "help_requests" DROP CONSTRAINT "help_requests_communityId_fkey";

-- DropForeignKey
ALTER TABLE "help_requests" DROP CONSTRAINT "help_requests_userId_fkey";

-- DropForeignKey
ALTER TABLE "manager_support_requests" DROP CONSTRAINT "manager_support_requests_userId_fkey";

-- DropForeignKey
ALTER TABLE "opportunities" DROP CONSTRAINT "opportunities_communityId_fkey";

-- DropForeignKey
ALTER TABLE "poll_options" DROP CONSTRAINT "poll_options_pollId_fkey";

-- DropForeignKey
ALTER TABLE "poll_votes" DROP CONSTRAINT "poll_votes_pollId_fkey";

-- DropForeignKey
ALTER TABLE "poll_votes" DROP CONSTRAINT "poll_votes_pollOptionId_fkey";

-- DropForeignKey
ALTER TABLE "poll_votes" DROP CONSTRAINT "poll_votes_userId_fkey";

-- DropForeignKey
ALTER TABLE "polls" DROP CONSTRAINT "polls_postId_fkey";

-- DropForeignKey
ALTER TABLE "pool_likes" DROP CONSTRAINT "pool_likes_poolId_fkey";

-- DropForeignKey
ALTER TABLE "pool_likes" DROP CONSTRAINT "pool_likes_userId_fkey";

-- DropForeignKey
ALTER TABLE "pool_members" DROP CONSTRAINT "pool_members_poolId_fkey";

-- DropForeignKey
ALTER TABLE "pool_members" DROP CONSTRAINT "pool_members_userId_fkey";

-- DropForeignKey
ALTER TABLE "pools" DROP CONSTRAINT "pools_chatId_fkey";

-- DropForeignKey
ALTER TABLE "pools" DROP CONSTRAINT "pools_communityId_fkey";

-- DropForeignKey
ALTER TABLE "posts" DROP CONSTRAINT "posts_authorId_fkey";

-- DropForeignKey
ALTER TABLE "posts" DROP CONSTRAINT "posts_communityId_fkey";

-- DropForeignKey
ALTER TABLE "reactions" DROP CONSTRAINT "reactions_commentId_fkey";

-- DropForeignKey
ALTER TABLE "reactions" DROP CONSTRAINT "reactions_postId_fkey";

-- DropForeignKey
ALTER TABLE "reactions" DROP CONSTRAINT "reactions_userId_fkey";

-- DropForeignKey
ALTER TABLE "resources" DROP CONSTRAINT "resources_communityId_fkey";

-- DropForeignKey
ALTER TABLE "reviews" DROP CONSTRAINT "reviews_communityId_fkey";

-- DropIndex
DROP INDEX "chats_communityId_idx";

-- DropIndex
DROP INDEX "opportunities_communityId_approvalStatus_idx";

-- DropIndex
DROP INDEX "reports_communityId_status_idx";

-- DropIndex
DROP INDEX "reviews_communityId_authorId_category_key";

-- DropIndex
DROP INDEX "reviews_communityId_category_idx";

-- Data safety (1/2): historical community-manager reviews are meaningless
-- without their community context — delete them before dropping the column.
DELETE FROM "reviews" WHERE category = 'COMMUNITY_MANAGERS';

-- AlterTable
ALTER TABLE "reviews" DROP COLUMN "communityId";

-- Data safety (2/2): COMMUNITY-type chats have no title of their own today;
-- backfill from the community name before dropping communityId so they don't
-- render as unnamed chats afterward.
UPDATE "chats" c SET title = cm.name
FROM "communities" cm
WHERE c."communityId" = cm.id AND c.title IS NULL;

-- AlterTable
ALTER TABLE "chats" DROP COLUMN "communityId";

-- AlterTable
ALTER TABLE "complaints" DROP COLUMN "communityId";

-- AlterTable
ALTER TABLE "opportunities" DROP COLUMN "communityId";

-- AlterTable
ALTER TABLE "reports" DROP COLUMN "communityId";

-- AlterTable
ALTER TABLE "resources" DROP COLUMN "communityId";

-- DropTable
DROP TABLE "ad_cards";

-- DropTable
DROP TABLE "bookmarks";

-- DropTable
DROP TABLE "comments";

-- DropTable
DROP TABLE "communities";

-- DropTable
DROP TABLE "community_head_applications";

-- DropTable
DROP TABLE "community_members";

-- DropTable
DROP TABLE "discount_claims";

-- DropTable
DROP TABLE "help_requests";

-- DropTable
DROP TABLE "manager_support_requests";

-- DropTable
DROP TABLE "poll_options";

-- DropTable
DROP TABLE "poll_votes";

-- DropTable
DROP TABLE "polls";

-- DropTable
DROP TABLE "pool_likes";

-- DropTable
DROP TABLE "pool_members";

-- DropTable
DROP TABLE "pools";

-- DropTable
DROP TABLE "posts";

-- DropTable
DROP TABLE "reactions";

-- DropEnum
DROP TYPE "CommunityRole";

-- DropEnum
DROP TYPE "CommunityType";

-- DropEnum
DROP TYPE "CommunityVisibility";

-- DropEnum
DROP TYPE "PostKind";

-- DropEnum
DROP TYPE "PostStatus";

-- DropEnum
DROP TYPE "PostType";

-- DropEnum
DROP TYPE "ReactionType";
