// Shared Field -> Degree -> Specialization[] taxonomy, used to drive the
// cascading course selector in the onboarding profile form and to help
// admins pick consistent field/degree names when adding a college's courses.
export const COURSE_TAXONOMY: Record<string, Record<string, string[]>> = {
  Engineering: {
    Diploma: ['Civil Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Computer Engineering', 'Electronics Engineering'],
    'B.Tech': [
      'Computer Science Engineering (CSE)',
      'Artificial Intelligence & Machine Learning (AI & ML)',
      'Information Technology (IT)',
      'Data Science',
      'Electronics & Communication Engineering (ECE)',
      'Electrical Engineering (EE)',
      'Mechanical Engineering',
      'Civil Engineering',
      'Chemical Engineering',
      'Aerospace Engineering',
      'Biotechnology Engineering',
      'Mechatronics Engineering',
      'Robotics Engineering',
      'Automobile Engineering',
    ],
    'B.E.': ['Computer Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Electrical Engineering', 'Electronics Engineering'],
    'M.Tech': ['Computer Science', 'Artificial Intelligence', 'Data Science', 'Cyber Security', 'Robotics', 'VLSI Design', 'Structural Engineering'],
    'M.E.': ['Mechanical Engineering', 'Civil Engineering', 'Electrical Engineering', 'Computer Engineering'],
    'Ph.D.': ['Computer Science', 'Artificial Intelligence', 'Mechanical Engineering', 'Civil Engineering', 'Electronics Engineering', 'Electrical Engineering'],
  },
  Medical: {
    MBBS: [],
    BDS: [],
    BAMS: [],
    BHMS: [],
    BUMS: [],
    'B.Sc. Nursing': ['General Nursing', 'Critical Care', 'Pediatric Nursing'],
    BPT: ['Sports Physiotherapy', 'Neurology', 'Orthopedics'],
    BOT: ['Pediatric OT', 'Neuro OT'],
    BMLT: ['Pathology', 'Microbiology', 'Biochemistry'],
    MD: ['General Medicine', 'Pediatrics', 'Radiology', 'Dermatology', 'Psychiatry'],
    MS: ['General Surgery', 'Orthopedics', 'ENT', 'Ophthalmology', 'Obstetrics & Gynecology'],
    MDS: ['Orthodontics', 'Oral Surgery', 'Prosthodontics'],
    DM: ['Cardiology', 'Neurology', 'Gastroenterology'],
    'M.Ch.': ['Neurosurgery', 'Urology', 'Plastic Surgery'],
    'Ph.D.': ['Anatomy', 'Physiology', 'Pharmacology', 'Microbiology'],
  },
  'Business & Management': {
    BBA: ['Marketing', 'Finance', 'HR', 'Business Analytics', 'International Business'],
    BBM: ['Marketing', 'Finance', 'Operations'],
    BMS: ['Marketing', 'Finance', 'Entrepreneurship'],
    'B.Com': ['Accounting', 'Taxation', 'Banking'],
    'B.Com (Hons.)': ['Accounting', 'Finance', 'Economics'],
    MBA: ['Marketing', 'Finance', 'HR', 'Operations', 'Business Analytics', 'IT', 'International Business'],
    PGDM: ['Marketing', 'Finance', 'HR'],
    'M.Com': ['Accounting', 'Finance', 'Taxation'],
    'Executive MBA': ['Strategy', 'Leadership', 'Finance'],
    'Ph.D.': ['Management', 'Finance', 'Marketing', 'Economics'],
  },
  'Arts & Humanities': {
    BA: ['English', 'History', 'Political Science', 'Psychology', 'Sociology', 'Economics'],
    'BA (Hons.)': ['English', 'Psychology', 'Economics', 'Political Science'],
    BFA: ['Painting', 'Sculpture', 'Applied Arts'],
    BPA: ['Music', 'Dance', 'Theatre'],
    MA: ['English', 'Psychology', 'History', 'Sociology'],
    MFA: ['Painting', 'Sculpture', 'Visual Arts'],
    MPA: ['Music', 'Dance', 'Theatre'],
    'Ph.D.': ['English', 'Psychology', 'History', 'Sociology'],
  },
  Law: {
    LLB: [],
    'BA LLB': [],
    'BBA LLB': [],
    'B.Com LLB': [],
    'B.Sc. LLB': [],
    LLM: ['Corporate Law', 'Criminal Law', 'Constitutional Law', 'Intellectual Property Law'],
    'Ph.D.': ['Corporate Law', 'Criminal Law', 'Constitutional Law'],
  },
  Science: {
    'B.Sc.': ['Physics', 'Chemistry', 'Mathematics', 'Biotechnology', 'Microbiology', 'Computer Science', 'Statistics'],
    'B.Sc. (Hons.)': ['Physics', 'Chemistry', 'Mathematics', 'Biotechnology'],
    'M.Sc.': ['Physics', 'Chemistry', 'Mathematics', 'Data Science', 'Biotechnology'],
    'Integrated M.Sc.': ['Physics', 'Chemistry', 'Mathematics'],
    'Ph.D.': ['Physics', 'Chemistry', 'Mathematics', 'Biotechnology'],
  },
  Pharmacy: {
    'D.Pharm': [],
    'B.Pharm': ['Pharmacology', 'Pharmaceutics', 'Pharmaceutical Chemistry'],
    'Pharm.D': ['Clinical Pharmacy', 'Hospital Pharmacy'],
    'M.Pharm': ['Pharmacology', 'Pharmaceutics', 'Quality Assurance'],
    'Ph.D.': ['Pharmacology', 'Pharmaceutics', 'Pharmaceutical Chemistry'],
  },
  Architecture: {
    'B.Arch': ['Sustainable Architecture', 'Urban Design', 'Landscape Architecture'],
    'M.Arch': ['Urban Planning', 'Interior Architecture', 'Landscape Design'],
    'Bachelor of Planning (B.Plan)': ['Urban Planning', 'Regional Planning'],
    'Master of Planning (M.Plan)': ['Transport Planning', 'Environmental Planning', 'Urban Planning'],
    'Ph.D.': ['Architecture', 'Urban Planning', 'Sustainable Design'],
  },
  Agriculture: {
    'B.Sc. Agriculture': ['Agronomy', 'Horticulture', 'Soil Science', 'Plant Pathology'],
    'B.Tech Agricultural Engineering': ['Farm Machinery', 'Irrigation', 'Food Processing'],
    'M.Sc. Agriculture': ['Agronomy', 'Genetics', 'Horticulture'],
    'M.Tech Agricultural Engineering': ['Farm Power', 'Irrigation Engineering'],
    'MBA Agribusiness': ['Agri Marketing', 'Supply Chain'],
    'Ph.D.': ['Agronomy', 'Genetics', 'Soil Science'],
  },
  Education: {
    'D.El.Ed.': [],
    'B.Ed.': ['Mathematics', 'Science', 'English', 'Social Science'],
    'Integrated B.Ed.': ['BA B.Ed.', 'B.Sc. B.Ed.', 'B.Com B.Ed.'],
    'M.Ed.': ['Educational Leadership', 'Curriculum Design', 'Educational Technology'],
    'Ph.D.': ['Education', 'Educational Psychology', 'Curriculum Studies'],
  },
  Design: {
    'B.Des.': ['UI/UX Design', 'Product Design', 'Fashion Design', 'Graphic Design', 'Animation'],
    'M.Des.': ['UX Design', 'Industrial Design', 'Interaction Design'],
    BFA: ['Applied Arts', 'Visual Arts'],
    MFA: ['Visual Arts', 'Sculpture'],
    'Ph.D.': ['Design', 'Visual Communication', 'Industrial Design'],
  },
  'Hotel Management': {
    'Diploma in Hotel Management': ['Food Production', 'Bakery', 'Front Office'],
    BHM: ['Hospitality Management', 'Food & Beverage', 'Front Office'],
    BHMCT: ['Catering Technology', 'Hospitality Management'],
    'B.Sc. Hospitality & Hotel Administration': ['Hotel Operations', 'Tourism'],
    MHM: ['Hospitality Management', 'Tourism Management'],
    'MBA Hospitality Management': ['Hotel Operations', 'Tourism', 'Event Management'],
    'Ph.D.': ['Hospitality Management', 'Tourism', 'Hotel Administration'],
  },
};

export const COURSE_FIELDS = Object.keys(COURSE_TAXONOMY);
